### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by keichan34** [unvt/sprite-one#16]
Is it possible to release a new version with the fixes to #11? I want to get a new version of charites out that fixes the bug

**Comment by smellman** [comment]
https://www.npmjs.com/package/@unvt/sprite-one published!

**Comment by keichan34** [comment]
@smellman Thanks! However, when I was debugging some spritesheets with missing sprites, I found that while the `src` directory has the recent files, the compiled files don't seem to have been updated: https://www.npmjs.com/package/@unvt/sprite-one?activeTab=explore
Can you double check and fix the release?

**Comment by smellman** [comment]
I forgot npm run build before. I just release 0.0.8.

**Comment by keichan34** [comment]
Looks good. Thanks!
